#!/bin/bash
# Laihdutanyt - Ubuntu Quick Start Script
# This script helps you quickly set up and test the application on Ubuntu LTS
# Script generated by Claude 4.5 AI to help the auditors of this work, which 
# was developed on Win11

set -e  # Exit on error

echo "======================================"
echo "  Laihdutanyt - Ubuntu Quick Start"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_success() {
    echo -e "${GREEN} $1${NC}"
}

print_error() {
    echo -e "${RED} $1${NC}"
}

print_info() {
    echo -e "${YELLOW}  $1${NC}"
}

# Check if we're in the right directory
if [ ! -f "pyproject.toml" ]; then
    print_error "pyproject.toml not found. Please run this script from the project root directory."
    exit 1
fi

print_success "Found project directory"

# Check Python 3.10+
echo ""
print_info "Checking Python version..."
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
    PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
    PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
    
    if [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -ge 10 ]; then
        print_success "Python installed: $PYTHON_VERSION (meets requirement: 3.10+)"
    else
        print_error "Python $PYTHON_VERSION found, but 3.10+ required"
        echo "Please install Python 3.10 or newer:"
        echo "  sudo add-apt-repository ppa:deadsnakes/ppa"
        echo "  sudo apt update"
        echo "  sudo apt install python3.10 python3.10-venv python3.10-tk"
        echo "  # Or use python3.11 or python3.12"
        exit 1
    fi
else
    print_error "Python 3 not found"
    echo "Please install Python 3.10 or newer"
    exit 1
fi

# Check Tkinter
echo ""
print_info "Checking Tkinter..."
if python3 -c "import tkinter" 2>/dev/null; then
    print_success "Tkinter is installed"
else
    print_error "Tkinter not found"
    echo "Please install Tkinter for your Python version:"
    echo "  sudo apt install python3-tk"
    exit 1
fi

# Check Poetry
echo ""
print_info "Checking Poetry..."
if command -v poetry &> /dev/null; then
    POETRY_VERSION=$(poetry --version)
    print_success "Poetry installed: $POETRY_VERSION"
else
    print_error "Poetry not found"
    echo "Please install Poetry:"
    echo "  curl -sSL https://install.python-poetry.org | python3.11 -"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    exit 1
fi

# Configure Poetry to use Python 3.11
echo ""
print_info "Configuring Poetry to use Python 3.11..."
poetry env use python3.11
print_success "Poetry configured"

# Install dependencies
echo ""
print_info "Installing dependencies (this may take 2-5 minutes)..."
poetry install
print_success "Dependencies installed"

# Check if database exists
echo ""
if [ -f "src/data/laihdutanyt.db" ]; then
    print_info "Database already exists"
    read -p "Do you want to reinitialize the database? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm src/data/laihdutanyt.db
        print_info "Initializing fresh database..."
        poetry run invoke init-db
        print_success "Database initialized"
    fi
else
    print_info "Initializing database..."
    poetry run invoke init-db
    print_success "Database initialized"
fi

# Ask about sample data
echo ""
read -p "Do you want to import sample data (foods & activities)? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    print_info "Importing sample foods..."
    poetry run python src/scripts/import_foods.py
    print_success "Foods imported"
    
    print_info "Importing sample activities..."
    poetry run python src/scripts/import_activities.py
    print_success "Activities imported"
fi

# Run tests
echo ""
read -p "Do you want to run tests? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    print_info "Running tests..."
    poetry run invoke test
    print_success "Tests completed"
fi

# Coverage report
echo ""
read -p "Do you want to generate coverage report? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    print_info "Generating coverage report..."
    poetry run invoke coverage-report
    print_success "Coverage report generated"
fi

# Final summary
echo ""
echo "======================================"
echo "  Setup Complete!"
echo "======================================"
echo ""
print_success "All systems ready!"
echo ""
echo "To start the application:"
echo "  poetry run invoke start"
echo ""
echo "Or:"
echo "  poetry run python src/main.py"
echo ""
echo "Demo credentials:"
echo "  User: testuser / test123 (create via Register)"
echo "  Admin: admin / admin123"
echo ""
echo "Available commands:"
echo "  poetry run invoke test          # Run tests"
echo "  poetry run invoke coverage      # Run tests with coverage"
echo "  poetry run invoke coverage-report # Show coverage report"
echo "  poetry run invoke lint          # Run linter"
echo "  poetry run invoke format        # Format code"
echo "  poetry run invoke --list        # Show all tasks"
echo ""

# Ask if user wants to start the app now
read -p "Do you want to start the application now? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    print_info "Starting Laihdutanyt..."
    poetry run invoke start
fi

print_success "Script completed!"
