# generoitu koodi alkaa
import sqlite3

# Note:
# *** The following code is a model for direct DB-connection-testing 
# and it is generated by MS Copilot ***

import sqlite3

class DatabaseService:
    def __init__(self, db_path):
        self.conn = sqlite3.connect(db_path)
        self.cursor = self.conn.cursor()
        self.initialize_db()

    def initialize_db(self):
        # Create the Band table
        self.cursor.execute('''
        CREATE TABLE IF NOT EXISTS band (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            bandgearbundle_id INTEGER NOT NULL,
            bandname TEXT NOT NULL,
            bandimage_path TEXT,
            bandsocmedgroupname TEXT
        )
        ''')
        self.conn.commit()

    def add_band(self, band):
        self.cursor.execute('''
        INSERT INTO band (bandgearbundle_id, bandname, bandimage_path, bandsocmedgroupname)
        VALUES (?, ?, ?, ?)
        ''', (band['bandgearbundle_id'], band['bandname'], band['bandimage_path'], band['bandsocmedgroupname']))
        self.conn.commit()

    def get_band_by_name(self, bandname):
        self.cursor.execute('''
        SELECT * FROM band WHERE bandname = ?
        ''', (bandname,))
        return self.cursor.fetchone()

    def close(self):
        self.conn.close()

# Example usage
if __name__ == "__main__":
    db_service = DatabaseService('soundslite_v1.db')

    new_band = {
        'bandgearbundle_id': 1,
        'bandname': 'The Four Camels',
        'bandimage_path': '/images/camels.png',
        'bandsocmedgroupname': 'rockers_group'
    }
    db_service.add_band(new_band)
    # generoitu koodi päättyy. 

    band = db_service.get_band_by_name('The Four Camels')
    print(band[2]) 

    db_service.close()
    # generoitu koodi päättyy. 
