from sqlalchemy import create_engine, Column, Integer, String, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

class DatabaseService:
    # Note:
    # *** The following code is just for DB-testing and it is generated by MS Copilot ***
    def __init__(self, db_url):
        self.engine = create_engine(db_url)
        Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        
    # get db connection session
    def get_session(self):
        return self.Session()

    # methods for CRUD operations: Create = add, Read = get
    def add_band(self, band):
        session = self.get_session()
        session.add(band)
        session.commit()
        session.close()

    def get_band_by_name(self, bandname):
        session = self.get_session()
        band = session.query(Band).filter(Band.bandname == bandname).first()
        session.close()
        return band
    
    def add_artist(self, artist):
        session = self.get_session()
        session.add(artist)
        session.commit()
        session.close()

    def get_artist_by_name(self, artistname):
        session = self.get_session()
        artist = session.query(Artist).filter(Artist.artistname == artistname).first()
        session.close()
        return artist

    def add_gearbundle(self, gearbundle):
        session = self.get_session()
        session.add(gearbundle)
        session.commit()
        session.close()

    def get_gearbundle_by_name(self, gearbundlename):
        session = self.get_session()
        gearbundle = session.query(Gearbundle).filter(Gearbundle.gearbundlename == gearbundlename).first()
        session.close()
        return gearbundle
    
    def add_gearbundlesound(self, gearbundlesound):
        session = self.get_session()
        session.add(gearbundlesound)
        session.commit()
        session.close()

    def get_gearbundlesound_by_name(self, gearbpresetname):
        session = self.get_session()
        gearbundlesound = session.query(Gearbundlesound).filter(Gearbundlesound.gearbpresetname == gearbpresetname).first()
        session.close()
        return gearbundlesound
    
    def add_gear(self, gear):
        session = self.get_session()
        session.add(gear)
        session.commit()
        session.close()

    def get_gear_by_name(self, gearname):
        session = self.get_session()
        gear = session.query(Gear).filter(Gear.gearname == gearname).first()
        session.close()
        return gear

    def add_bandgearbundle(self, bandgearbundle):
        session = self.get_session()
        session.add(bandgearbundle)
        session.commit()
        session.close()

    def get_bandgearbundle_by_id(self, bandgearbundleID):
        session = self.get_session()
        bandgearbundle = session.query(Bandgearbundle).filter(BandgearbundleID == bandgearbundleID).first()
        session.close()
        return bandgearbundle

    def add_artistgearbundle(self, band):
        session = self.get_session()
        session.add(band)
        session.commit()
        session.close()
        
    def get_artistgearbundle_by_id(self, artistgearbundleID):
        session = self.get_session()
        artistgearbundle = session.query(artistgearbundle).filter(artistgearbundleID == artistgearbundleID).first()
        session.close()
        return artistgearbundle
